version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./docker/php
    working_dir: /code
    volumes:
      - ./:/code

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      #POSTGRES_DB: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      # POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: ${POSTGRES_USER:-app}
      # POSTGRES_USER: admin
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  database_data:
